name: Pipeline de Integração Contínua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o código
        uses: actions/checkout@v4

      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalando dependências
        run: npm install

      - name: Verificando padronização do código (Lint)
        run: npm run eslint

      - name: Executando os testes
        run: npm test
