name: Pipeline de Integração Contínua

# Define quando o CI deve rodar
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validacao:
    runs-on: ubuntu-latest # O GitHub vai criar uma máquina virtual Linux para nós

    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      - name: Configurando o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalando as dependências (Jest)
        run: npm install

      - name: Executando os testes unitários
        run: npm test
